import React from "react";
import cx from "classnames";
import { NavList, NavItem, NavLink } from "$components/NavList";
import "./styles.scss";

export default function AutoLinks({ className }) {
  // TODO: This should be auto-generated by MDX
  return (
    <nav className={cx(className, "AutoLinks")}>
      <h3 className="AutoLinks__heading">On This Page</h3>
      <NavList className="AutoLinks__NavList">
        <NavItem>
          <NavLink href="#heading-1">Heading 1</NavLink>
        </NavItem>
        <NavItem>
          <NavLink href="#heading-2">Heading 1</NavLink>
        </NavItem>
        <NavItem>
          <NavLink href="#heading-3">Heading 3</NavLink>
        </NavItem>
        <NavItem>
          <NavLink href="#heading-4">Heading 4</NavLink>
        </NavItem>
      </NavList>
    </nav>
  );
}
